# Convert Cleaned Data into Dictionary

This notebook will load in Cleaned_data.csv and adjust the formatting for reading in lists as cell values. It will also convert an input of Cleaned Resume text, the identified skill words, and the start/end indices of these words, and produce the dictionary format which can be used for training an NER model

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import warnings
warnings.filterwarnings("ignore")

Unfortunately when you save an array in Python it converts it to a string, below is a function for fixing the data when you read it in

In [3]:
data = pd.read_csv('Cleaned_data.csv')#read in cleaned data
data

,Unnamed: 0,Category,Resume,Cleaned_text,indices,skill_words
0,0,Data Science,Skills * Programming Languages: Python (pandas...,Skills Programming Languages Python pandas num...,"[array([[ 7, 28],\n [ 29, 35],\n ...","[['Programming Languages', 'Python', 'pandas',..."
1,1,Data Science,Education Details \r\nMay 2013 to May 2017 B.E...,Education Details May 2013 to May 2017 B.E U...,"[array([[ 464, 466],\n [ 654, 659],\n ...","[['ML', 'steps', 'machine learning', 'encoding..."
2,2,Data Science,"Areas of Interest Deep Learning, Control Syste...",Areas of Interest Deep Learning Control System...,"[array([[ 18, 31],\n [ 47, 65],\n ...","[['Deep Learning', 'Design Programming', 'Mach..."
3,3,Data Science,Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...,Skills R Python SAP HANA Tableau SAP HANA...,"[array([[ 8, 9],\n [ 11, 17],\n ...","[['R', 'Python', 'SAP HANA', 'Tableau', 'SAP H..."
4,4,Data Science,"Education Details \r\n MCA YMCAUST, Faridab...",Education Details MCA YMCAUST Faridabad Ha...,"[array([[ 52, 64],\n [325, 333]])]","[['Data Science', 'Database']]"
...,...,...,...,...,...,...
957,957,Testing,Computer Skills: â¢ Proficient in MS office (...,Computer Skills Proficient in MS office Word ...,"[array([[ 0, 15],\n [ 34, 40],\n ...","[['Computer Skills', 'office', 'Word', 'Basic'..."
958,958,Testing,â Willingness to accept the challenges. â ...,Willingness to accept the challenges. Positi...,"[array([[ 347, 358],\n [ 490, 501],\n ...","[['Electronics', 'Electronics', 'Testing', 'El..."
959,959,Testing,"PERSONAL SKILLS â¢ Quick learner, â¢ Eagerne...",PERSONAL SKILLS Quick learner Eagerness to l...,"[array([[ 90, 100],\n [ 408, 416],\n ...","[['leadership', 'Research', 'Testing', 'Testin..."
960,960,Testing,COMPUTER SKILLS & SOFTWARE KNOWLEDGE MS-Power ...,COMPUTER SKILLS & SOFTWARE KNOWLEDGE MS-Power ...,"[array([[ 0, 15],\n [ 57, 63],\n ...","[['COMPUTER SKILLS', 'Office', 'C', 'PCB Desig..."
961,961,Testing,Skill Set OS Windows XP/7/8/8.1/10 Database MY...,Skill Set OS Windows XP 7 8 8.1 10 Database MY...,"[array([[ 13, 23],\n [ 35, 43],\n ...","[['Windows XP', 'Database', 'MYSQL', 'sql serv..."

In [4]:
def convert_string_to_array(string):#this function converts a string into a numpy array
    index_list = string.split('],[') #split string
    index_list[0] = index_list[0][1:] #cut off brackets [ and ]
    index_list[-1] = index_list[-1][:-1]
    for i in range(len(index_list)):
        j = (np.array(index_list[i].split(',')))#split each element
        if i == 0:
            index_array = j
        else:
            index_array = np.vstack( [index_array, j] )#stack
    return(index_array)

def fix_df_arrays(data): #cleaning up the list columns (get rid of unwanted characters)
    data['indices'] = data['indices'].str.replace('\n','')
    data['indices'] = data['indices'].str.replace('array','')
    data['indices'] = data['indices'].str.replace('[([','')
    data['indices'] = data['indices'].str.replace('])]','')
    data['indices'] = data['indices'].str.replace(' ','')
    data['skill_words'] = data['skill_words'].str.replace('[[','')
    data['skill_words'] = data['skill_words'].str.replace(']]','')
    data['skill_words'] = data['skill_words'].str.replace("'",'')
    
    data['index_array'] =data['indices']
    
    for i in range(len(data)):
        data['index_array'][i] = convert_string_to_array(data['indices'][i])#convert indices string into numpy array
        
    return(data[['Category','Cleaned_text','skill_words','index_array']])#grab just the columns we want

In [5]:
data = fix_df_arrays(data) #run function

In [6]:
data

,Category,Cleaned_text,skill_words,index_array
0,Data Science,Skills Programming Languages Python pandas num...,"Programming Languages, Python, pandas, numpy, ...","[[7, 28], [29, 35], [36, 42], [43, 48], [49, 5..."
1,Data Science,Education Details May 2013 to May 2017 B.E U...,"ML, steps, machine learning, encoding, feature...","[[464, 466], [654, 659], [663, 679], [729, 737..."
2,Data Science,Areas of Interest Deep Learning Control System...,"Deep Learning, Design Programming, Machinery, ...","[[18, 31], [47, 65], [85, 94], [95, 110], [111..."
3,Data Science,Skills R Python SAP HANA Tableau SAP HANA...,"R, Python, SAP HANA, Tableau, SAP HANA, SQL, S...","[[8, 9], [11, 17], [19, 27], [29, 36], [38, 46..."
4,Data Science,Education Details MCA YMCAUST Faridabad Ha...,"Data Science, Database","[[52, 64], [325, 333]]"
...,...,...,...,...
957,Testing,Computer Skills Proficient in MS office Word ...,"Computer Skills, office, Word, Basic, Excel, C...","[[0, 15], [34, 40], [41, 45], [46, 51], [52, 5..."
958,Testing,Willingness to accept the challenges. Positi...,"Electronics, Electronics, Testing, Electronics...","[[347, 358], [490, 501], [570, 577], [587, 598..."
959,Testing,PERSONAL SKILLS Quick learner Eagerness to l...,"leadership, Research, Testing, Testing, Transf...","[[90, 100], [408, 416], [628, 635], [665, 672]..."
960,Testing,COMPUTER SKILLS & SOFTWARE KNOWLEDGE MS-Power ...,"COMPUTER SKILLS, Office, C, PCB Design, Matlab...","[[0, 15], [57, 63], [64, 65], [74, 84], [105, ..."
961,Testing,Skill Set OS Windows XP 7 8 8.1 10 Database MY...,"Windows XP, Database, MYSQL, sql server, Langu...","[[13, 23], [35, 43], [44, 49], [50, 60], [78, ..."

## Create a dictionary

Now we need to take the data in this csv and convert it to a dictionary form so it can work with spaCy

In [7]:
#this takes the text, a list of the skill words, and the indices list
#and creates a dictionary of the format desired for training
def create_dictionary(sample_text,indices,words):
    data_dict={}
    data_dict['content']=sample_text
    
    d={}
    starts = indices[:,0]
    ends = indices[:,1]
    d["text"]=words
    d["start"]=starts
    d["end"]=ends
    d = [{'text': words, 'start': starts, 'end': ends} for words,starts,ends in zip(d['text'], d['start'],d['end'])]
    
    items = []
    label_dict={}
    label_dict['label'] = 'SKILL'
    label_dict['points']  = {}
    for i in range(len(d)):
        label_dict = {'label':'SKILL','points':{'text':d[i]['text'],'start':d[i]['start'],'end':d[i]['end']}}
        items.append(label_dict)
        
    data_dict['annotations']=items
    return(data_dict)

In [8]:
#sample_text, indices, words are taken directly from the columns
i = 0 #for the first row
create_dictionary(data['Cleaned_text'][i],data['index_array'][i], data['skill_words'][i].split(','))#the words column needs splitting

{'content': 'Skills Programming Languages Python pandas numpy scipy scikit-learn matplotlib Sql Java JavaScript JQuery. Machine learning Regression SVM Nave Bayes KNN Random Forest Decision Trees Boosting techniques Cluster Analysis Word Embedding Sentiment Analysis Natural Language processing Dimensionality reduction Topic Modelling LDA NMF PCA & Neural Nets. Database Visualizations Mysql SqlServer Cassandra Hbase ElasticSearch D3.js DC.js Plotly kibana matplotlib ggplot Tableau. Others Regular Expression HTML CSS Angular 6 Logstash Kafka Python Flask Git Docker computer vision - Open CV and understanding of Deep learning.Education Details Data Science Assurance Associate Data Science Assurance Associate - Ernst & Young LLP Skill Details  JAVASCRIPT- Exprience - 24 months jQuery- Exprience - 24 months Python- Exprience - 24 monthsCompany Details  company - Ernst & Young LLP description - Fraud Investigations and Dispute Services  Assurance TECHNOLOGY ASSISTED REVIEW TAR Technology Assisted Review assists in accelerating the review process and run analytics and generate reports.  Core member of a team helped in developing automated review platform tool from scratch for assisting E discovery domain this tool implements predictive coding and topic modelling by automating reviews resulting in reduced labor costs and time spent during the lawyers review.  Understand the end to end flow of the solution doing research and development for classification models predictive analysis and mining of the information present in text data. Worked on analyzing the outputs and precision monitoring for the entire tool.  TAR assists in predictive coding topic modelling from the evidence by following EY standards. Developed the classifier models in order to identify "red flags" and fraud-related issues.  Tools & Technologies Python scikit-learn tfidf word2vec doc2vec cosine similarity Nave Bayes LDA NMF for topic modelling Vader and text blob for sentiment analysis. Matplot lib Tableau dashboard for reporting.  MULTIPLE DATA SCIENCE AND ANALYTIC PROJECTS USA CLIENTS TEXT ANALYTICS - MOTOR VEHICLE CUSTOMER REVIEW DATA Received customer feedback survey data for past one year. Performed sentiment Positive Negative & Neutral and time series analysis on customer comments across all 4 categories.  Created heat map of terms by survey category based on frequency of words Extracted Positive and Negative words across all the Survey categories and plotted Word cloud.  Created customized tableau dashboards for effective reporting and visualizations. CHATBOT Developed a user friendly chatbot for one of our Products which handle simple questions about hours of operation reservation options and so on.  This chat bot serves entire product related questions. Giving overview of tool via QA platform and also give recommendation responses so that user question to build chain of relevant answer.  This too has intelligence to build the pipeline of questions as per user requirement and asks the relevant recommended questions.  Tools & Technologies Python Natural language processing NLTK spacy topic modelling Sentiment analysis Word Embedding scikit-learn JavaScript JQuery SqlServer  INFORMATION GOVERNANCE Organizations to make informed decisions about all of the information they store. The integrated Information Governance portfolio synthesizes intelligence across unstructured data sources and facilitates action to ensure organizations are best positioned to counter information risk.  Scan data from multiple sources of formats and parse different file formats extract Meta data information push results for indexing elastic search and created customized interactive dashboards using kibana.  Preforming ROT Analysis on the data which give information of data which helps identify content that is either Redundant Outdated or Trivial.  Preforming full-text search analysis on elastic search with predefined methods which can tag as PII personally identifiable information social security numbers addresses names etc. which frequently targeted during cyber-attacks. Tools & Technologies Python Flask Elastic Search Kibana  FRAUD ANALYTIC PLATFORM Fraud Analytics and investigative platform to review all red flag cases.  FAP is a Fraud Analytics and investigative platform with inbuilt case manager and suite of Analytics for various ERP systems.  It can be used by clients to interrogate their Accounting systems for identifying the anomalies which can be indicators of fraud by running advanced analytics Tools & Technologies HTML JavaScript SqlServer JQuery CSS Bootstrap Node.js D3.js DC.js',
 'annotations': [{'label': 'SKILL',
   'points': {'text': 'Programming Languages', 'start': '7', 'end': '28'}},
  {'label': 'SKILL',
   'points': {'text': ' Python', 'start': '29', 'end': '35'}},
  {'label': 'SKILL',
   'points': {'text': ' pandas', 'start': '36', 'end': '42'}},
  {'label': 'SKILL', 'points': {'text': ' numpy', 'start': '43', 'end': '48'}},
  {'label': 'SKILL', 'points': {'text': ' scipy', 'start': '49', 'end': '54'}},
  {'label': 'SKILL',
   'points': {'text': ' scikit-learn', 'start': '55', 'end': '67'}},
  {'label': 'SKILL',
   'points': {'text': ' matplotlib', 'start': '68', 'end': '78'}},
  {'label': 'SKILL', 'points': {'text': ' Sql', 'start': '79', 'end': '82'}},
  {'label': 'SKILL', 'points': {'text': ' Java', 'start': '83', 'end': '87'}},
  {'label': 'SKILL',
   'points': {'text': ' JavaScript', 'start': '88', 'end': '98'}},
  {'label': 'SKILL',
   'points': {'text': ' Machine learning', 'start': '107', 'end': '123'}},
  {'label': 'SKILL',
   'points': {'text': ' Forest', 'start': '161', 'end': '167'}},
  {'label': 'SKILL',
   'points': {'text': ' Decision Trees', 'start': '168', 'end': '182'}},
  {'label': 'SKILL',
   'points': {'text': ' Cluster Analysis', 'start': '203', 'end': '219'}},
  {'label': 'SKILL',
   'points': {'text': ' Word', 'start': '220', 'end': '224'}},
  {'label': 'SKILL',
   'points': {'text': ' Sentiment Analysis', 'start': '235', 'end': '253'}},
  {'label': 'SKILL',
   'points': {'text': ' Natural Language processing',
    'start': '254',
    'end': '281'}},
  {'label': 'SKILL',
   'points': {'text': ' Dimensionality reduction',
    'start': '282',
    'end': '306'}},
  {'label': 'SKILL', 'points': {'text': ' LDA', 'start': '323', 'end': '326'}},
  {'label': 'SKILL', 'points': {'text': ' PCA', 'start': '331', 'end': '334'}},
  {'label': 'SKILL',
   'points': {'text': ' Database', 'start': '350', 'end': '358'}},
  {'label': 'SKILL',
   'points': {'text': ' Mysql', 'start': '374', 'end': '379'}},
  {'label': 'SKILL',
   'points': {'text': ' Cassandra', 'start': '390', 'end': '399'}},
  {'label': 'SKILL',
   'points': {'text': ' Hbase', 'start': '400', 'end': '405'}},
  {'label': 'SKILL',
   'points': {'text': ' ElasticSearch', 'start': '406', 'end': '419'}},
  {'label': 'SKILL',
   'points': {'text': ' D3.js', 'start': '420', 'end': '425'}},
  {'label': 'SKILL',
   'points': {'text': ' kibana', 'start': '439', 'end': '445'}},
  {'label': 'SKILL',
   'points': {'text': ' matplotlib', 'start': '446', 'end': '456'}},
  {'label': 'SKILL',
   'points': {'text': ' HTML', 'start': '499', 'end': '503'}},
  {'label': 'SKILL', 'points': {'text': ' CSS', 'start': '504', 'end': '507'}},
  {'label': 'SKILL',
   'points': {'text': ' Angular', 'start': '508', 'end': '515'}},
  {'label': 'SKILL',
   'points': {'text': ' Logstash', 'start': '518', 'end': '526'}},
  {'label': 'SKILL',
   'points': {'text': ' Kafka', 'start': '527', 'end': '532'}},
  {'label': 'SKILL',
   'points': {'text': ' Python', 'start': '533', 'end': '539'}},
  {'label': 'SKILL',
   'points': {'text': ' Flask', 'start': '540', 'end': '545'}},
  {'label': 'SKILL', 'points': {'text': ' Git', 'start': '546', 'end': '549'}},
  {'label': 'SKILL',
   'points': {'text': ' Docker', 'start': '550', 'end': '556'}},
  {'label': 'SKILL',
   'points': {'text': ' computer vision', 'start': '557', 'end': '572'}},
  {'label': 'SKILL',
   'points': {'text': ' Data Science', 'start': '636', 'end': '648'}},
  {'label': 'SKILL',
   'points': {'text': ' Data Science', 'start': '669', 'end': '681'}},
  {'label': 'SKILL', 'points': {'text': ' LLP', 'start': '718', 'end': '721'}},
  {'label': 'SKILL', 'points': {'text': ' LLP', 'start': '871', 'end': '874'}},
  {'label': 'SKILL',
   'points': {'text': ' Fraud Investigations', 'start': '889', 'end': '909'}},
  {'label': 'SKILL',
   'points': {'text': ' TECHNOLOGY', 'start': '942', 'end': '952'}},
  {'label': 'SKILL', 'points': {'text': ' TAR', 'start': '969', 'end': '972'}},
  {'label': 'SKILL',
   'points': {'text': ' Technology', 'start': '973', 'end': '983'}},
  {'label': 'SKILL',
   'points': {'text': ' analytics', 'start': '1051', 'end': '1060'}},
  {'label': 'SKILL',
   'points': {'text': ' scratch', 'start': '1163', 'end': '1170'}},
  {'label': 'SKILL',
   'points': {'text': ' reviews', 'start': '1277', 'end': '1284'}},
  {'label': 'SKILL',
   'points': {'text': ' flow', 'start': '1387', 'end': '1391'}},
  {'label': 'SKILL',
   'points': {'text': ' research', 'start': '1414', 'end': '1422'}},
  {'label': 'SKILL',
   'points': {'text': ' classification', 'start': '1443', 'end': '1457'}},
  {'label': 'SKILL',
   'points': {'text': ' models', 'start': '1458', 'end': '1464'}},
  {'label': 'SKILL',
   'points': {'text': ' mining', 'start': '1489', 'end': '1495'}},
  {'label': 'SKILL',
   'points': {'text': ' TAR', 'start': '1616', 'end': '1619'}},
  {'label': 'SKILL',
   'points': {'text': ' models', 'start': '1735', 'end': '1741'}},
  {'label': 'SKILL',
   'points': {'text': ' Python', 'start': '1823', 'end': '1829'}},
  {'label': 'SKILL',
   'points': {'text': ' scikit-learn', 'start': '1830', 'end': '1842'}},
  {'label': 'SKILL',
   'points': {'text': ' LDA', 'start': '1895', 'end': '1898'}},
  {'label': 'SKILL',
   'points': {'text': ' Tableau', 'start': '1979', 'end': '1986'}},
  {'label': 'SKILL',
   'points': {'text': ' dashboard', 'start': '1987', 'end': '1996'}},
  {'label': 'SKILL',
   'points': {'text': ' DATA SCIENCE', 'start': '2022', 'end': '2034'}},
  {'label': 'SKILL',
   'points': {'text': ' TEXT ANALYTICS', 'start': '2069', 'end': '2083'}},
  {'label': 'SKILL',
   'points': {'text': ' MOTOR VEHICLE', 'start': '2086', 'end': '2099'}},
  {'label': 'SKILL',
   'points': {'text': ' CUSTOMER', 'start': '2100', 'end': '2108'}},
  {'label': 'SKILL',
   'points': {'text': ' customer', 'start': '2130', 'end': '2138'}},
  {'label': 'SKILL',
   'points': {'text': ' survey', 'start': '2148', 'end': '2154'}},
  {'label': 'SKILL',
   'points': {'text': ' one', 'start': '2169', 'end': '2172'}},
  {'label': 'SKILL',
   'points': {'text': ' time series analysis',
    'start': '2231',
    'end': '2251'}},
  {'label': 'SKILL',
   'points': {'text': ' customer', 'start': '2255', 'end': '2263'}},
  {'label': 'SKILL',
   'points': {'text': ' heat', 'start': '2307', 'end': '2311'}},
  {'label': 'SKILL',
   'points': {'text': ' map', 'start': '2312', 'end': '2315'}},
  {'label': 'SKILL',
   'points': {'text': ' survey', 'start': '2328', 'end': '2334'}},
  {'label': 'SKILL',
   'points': {'text': ' Survey', 'start': '2425', 'end': '2431'}},
  {'label': 'SKILL',
   'points': {'text': ' Word', 'start': '2455', 'end': '2459'}},
  {'label': 'SKILL',
   'points': {'text': ' tableau', 'start': '2487', 'end': '2494'}},
  {'label': 'SKILL',
   'points': {'text': ' dashboards', 'start': '2495', 'end': '2505'}},
  {'label': 'SKILL',
   'points': {'text': ' reporting', 'start': '2520', 'end': '2529'}},
  {'label': 'SKILL',
   'points': {'text': ' user friendly', 'start': '2570', 'end': '2583'}},
  {'label': 'SKILL',
   'points': {'text': ' one', 'start': '2596', 'end': '2599'}},
  {'label': 'SKILL',
   'points': {'text': ' options', 'start': '2683', 'end': '2690'}},
  {'label': 'SKILL',
   'points': {'text': ' chat', 'start': '2708', 'end': '2712'}},
  {'label': 'SKILL',
   'points': {'text': ' bot', 'start': '2713', 'end': '2716'}},
  {'label': 'SKILL',
   'points': {'text': ' intelligence', 'start': '2908', 'end': '2920'}},
  {'label': 'SKILL',
   'points': {'text': ' pipeline', 'start': '2934', 'end': '2942'}},
  {'label': 'SKILL',
   'points': {'text': ' Python', 'start': '3047', 'end': '3053'}},
  {'label': 'SKILL',
   'points': {'text': ' Natural language processing',
    'start': '3054',
    'end': '3081'}},
  {'label': 'SKILL',
   'points': {'text': ' NLTK', 'start': '3082', 'end': '3086'}},
  {'label': 'SKILL',
   'points': {'text': ' Sentiment analysis', 'start': '3109', 'end': '3127'}},
  {'label': 'SKILL',
   'points': {'text': ' Word', 'start': '3128', 'end': '3132'}},
  {'label': 'SKILL',
   'points': {'text': ' scikit-learn', 'start': '3143', 'end': '3155'}},
  {'label': 'SKILL',
   'points': {'text': ' JavaScript', 'start': '3156', 'end': '3166'}},
  {'label': 'SKILL',
   'points': {'text': ' JQuery', 'start': '3167', 'end': '3173'}},
  {'label': 'SKILL',
   'points': {'text': ' INFORMATION GOVERNANCE',
    'start': '3185',
    'end': '3207'}},
  {'label': 'SKILL',
   'points': {'text': ' Information Governance',
    'start': '3305',
    'end': '3327'}},
  {'label': 'SKILL',
   'points': {'text': ' intelligence', 'start': '3350', 'end': '3362'}},
  {'label': 'SKILL',
   'points': {'text': ' unstructured data', 'start': '3370', 'end': '3387'}},
  {'label': 'SKILL',
   'points': {'text': ' parse', 'start': '3540', 'end': '3545'}},
  {'label': 'SKILL',
   'points': {'text': ' indexing', 'start': '3616', 'end': '3624'}},
  {'label': 'SKILL',
   'points': {'text': ' search', 'start': '3633', 'end': '3639'}},
  {'label': 'SKILL',
   'points': {'text': ' dashboards', 'start': '3675', 'end': '3685'}},
  {'label': 'SKILL',
   'points': {'text': ' search analysis', 'start': '3865', 'end': '3880'}},
  {'label': 'SKILL',
   'points': {'text': ' search', 'start': '3892', 'end': '3898'}},
  {'label': 'SKILL',
   'points': {'text': ' PII', 'start': '3940', 'end': '3943'}},
  {'label': 'SKILL',
   'points': {'text': ' social security', 'start': '3980', 'end': '3995'}},
  {'label': 'SKILL',
   'points': {'text': ' numbers', 'start': '3996', 'end': '4003'}},
  {'label': 'SKILL',
   'points': {'text': ' Python', 'start': '4094', 'end': '4100'}},
  {'label': 'SKILL',
   'points': {'text': ' Flask', 'start': '4101', 'end': '4106'}},
  {'label': 'SKILL',
   'points': {'text': ' Search', 'start': '4115', 'end': '4121'}},
  {'label': 'SKILL',
   'points': {'text': ' Kibana', 'start': '4122', 'end': '4128'}},
  {'label': 'SKILL',
   'points': {'text': ' FRAUD', 'start': '4130', 'end': '4135'}},
  {'label': 'SKILL',
   'points': {'text': ' Fraud', 'start': '4154', 'end': '4159'}},
  {'label': 'SKILL',
   'points': {'text': ' Analytics', 'start': '4160', 'end': '4169'}},
  {'label': 'SKILL',
   'points': {'text': ' Fraud', 'start': '4237', 'end': '4242'}},
  {'label': 'SKILL',
   'points': {'text': ' Analytics', 'start': '4243', 'end': '4252'}},
  {'label': 'SKILL',
   'points': {'text': ' case', 'start': '4293', 'end': '4297'}},
  {'label': 'SKILL',
   'points': {'text': ' suite', 'start': '4310', 'end': '4315'}},
  {'label': 'SKILL',
   'points': {'text': ' Analytics', 'start': '4319', 'end': '4328'}},
  {'label': 'SKILL',
   'points': {'text': ' It', 'start': '4355', 'end': '4357'}},
  {'label': 'SKILL',
   'points': {'text': ' indicators', 'start': '4464', 'end': '4474'}},
  {'label': 'SKILL',
   'points': {'text': ' fraud', 'start': '4478', 'end': '4483'}},
  {'label': 'SKILL',
   'points': {'text': ' running', 'start': '4487', 'end': '4494'}},
  {'label': 'SKILL',
   'points': {'text': ' advanced', 'start': '4495', 'end': '4503'}},
  {'label': 'SKILL',
   'points': {'text': ' analytics', 'start': '4504', 'end': '4513'}},
  {'label': 'SKILL',
   'points': {'text': ' HTML', 'start': '4535', 'end': '4539'}},
  {'label': 'SKILL',
   'points': {'text': ' JavaScript', 'start': '4540', 'end': '4550'}},
  {'label': 'SKILL',
   'points': {'text': ' JQuery', 'start': '4561', 'end': '4567'}},
  {'label': 'SKILL',
   'points': {'text': ' CSS', 'start': '4568', 'end': '4571'}},
  {'label': 'SKILL',
   'points': {'text': ' Bootstrap', 'start': '4572', 'end': '4581'}},
  {'label': 'SKILL',
   'points': {'text': ' Node.js', 'start': '4582', 'end': '4589'}},
  {'label': 'SKILL',
   'points': {'text': ' D3.js', 'start': '4590', 'end': '4595'}}]}